language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"
  - "3.5"
  # pypy3 on Travis raises ImportError when psutil (which is used by succubus)
  # is imported.
  #- "pypy3"

install:
  # Work around for https://github.com/ImmobilienScout24/afp-alppaca/issues/13
  # With setup.cfg present, pip does not work.
  - rm -f setup.cfg
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
  
script: "pyb -X verify analyze"
after_success:
  - coveralls --verbose
